import React, { useEffect } from 'react';
import { motion } from 'motion/react';
import { Scale, FileText, AlertTriangle, Info, Calendar, Phone, MapPin } from 'lucide-react';
import { useTranslation } from '../contexts/LanguageContext';

export const TermsOfService: React.FC = () => {
  const { t, translateBatch, language } = useTranslation();

  const content = [
    "Terms of Service",
    "Last updated: January 2025",
    "By using KrushiSense, you agree to these terms. Please read them carefully. These terms are written in plain language — no legal jargon.",
    "1. What KrushiSense Is",
    "KrushiSense is an AI-assisted crop recommendation tool designed to help farmers in Maharashtra and across India make informed decisions about which crops to grow based on soil and environmental parameters.",
    "KrushiSense is a guidance tool — not a substitute for professional agricultural advice. Always verify recommendations with your local Krishi Vigyan Kendra (KVK) or a qualified agronomist before making major farming decisions.",
    "2. Accuracy Disclaimer",
    "Crop recommendations generated by KrushiSense are based on machine learning models trained on agricultural datasets. While we strive for accuracy, we make no guarantees about:",
    "The suitability of any recommended crop for your specific land.",
    "Crop yield, profit, or harvest outcomes.",
    "Accuracy of recommendations under extreme or unusual soil and climate conditions.",
    "Results if the input values you enter are inaccurate or estimated.",
    "For best results, use values from a certified soil test report. KVKs across Maharashtra offer soil testing from ₹100–₹200 per sample.",
    "3. No Liability for Crop Losses",
    "KrushiSense and its developers are not responsible for any crop failure, financial loss, or damage that may result from following recommendations provided by this application. Agriculture involves many unpredictable factors — weather, pests, market prices — that are beyond the scope of any recommendation tool. Use KrushiSense as one input among many, not as your only decision-making source.",
    "4. KVK Location Data",
    "The Krishi Vigyan Kendra locations, phone numbers, and service information shown on KrushiSense are sourced from ICAR official records and individual KVK websites. While we do our best to keep this information accurate, details may change. Always call ahead to confirm a KVK's services and hours before visiting.",
    "5. Fertilizer Recommendations",
    "Fertilizer dosage calculations shown on KrushiSense are based on ICAR published guidelines and standard agronomic formulas. These are estimates only. Actual fertilizer requirements vary by soil condition, irrigation, crop variety, and season. Consult an agronomist or your local KVK before applying fertilizers.",
    "6. Acceptable Use",
    "You agree not to:",
    "Use KrushiSense for any unlawful purpose.",
    "Attempt to reverse engineer, scrape, or copy the recommendation model or datasets.",
    "Misrepresent KrushiSense recommendations as certified agricultural advice.",
    "7. Availability",
    "KrushiSense is provided free of charge. We do not guarantee uninterrupted availability of the service. We may update, modify, or temporarily suspend the app at any time without prior notice.",
    "8. Changes to These Terms",
    "We may update these Terms of Service as the application evolves. Changes will be reflected on this page with an updated date. Continued use of KrushiSense after changes constitutes your acceptance of the new terms.",
    "9. Contact",
    "Questions about these terms? Contact us via the Contact Support page."
  ];

  useEffect(() => {
    translateBatch(content);
  }, [language]);

  return (
    <div className="max-w-4xl mx-auto px-6 py-20 md:py-32">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="space-y-16"
      >
        {/* Header */}
        <header className="border-b border-on-surface/10 pb-12">
          <div className="flex items-center gap-3 text-primary font-headline font-black uppercase tracking-widest text-xs mb-6">
            <Scale className="size-5" />
            <span>{t("Legal Agreement")}</span>
          </div>
          <h1 className="font-headline font-black text-5xl md:text-7xl tracking-tighter text-on-surface mb-8">
            {t("Terms of Service")}
          </h1>
          <div className="flex items-center gap-2 text-on-surface-variant font-body text-sm bg-surface-container-low w-fit px-4 py-2 rounded-full border border-on-surface/5">
            <Calendar className="size-4" />
            <span>{t("Last updated: January 2025")}</span>
          </div>
        </header>

        {/* Intro */}
        <section className="bg-primary/5 p-8 md:p-12 rounded-[2.5rem] border border-primary/10">
          <p className="font-body text-on-surface text-lg md:text-xl leading-relaxed italic">
            "{t("By using KrushiSense, you agree to these terms. Please read them carefully. These terms are written in plain language — no legal jargon.")}"
          </p>
        </section>

        {/* Content Sections */}
        <div className="space-y-12">
          {[
            { id: 1, title: "1. What KrushiSense Is", icon: <Info className="size-6" /> },
            { id: 2, title: "2. Accuracy Disclaimer", icon: <AlertTriangle className="size-6" /> },
            { id: 3, title: "3. No Liability for Crop Losses", icon: <Scale className="size-6" /> },
            { id: 4, title: "4. KVK Location Data", icon: <MapPin className="size-6" /> },
            { id: 5, title: "5. Fertilizer Recommendations", icon: <FileText className="size-6" /> },
            { id: 6, title: "6. Acceptable Use", icon: <Scale className="size-6" /> },
            { id: 7, title: "7. Availability", icon: <Calendar className="size-6" /> },
            { id: 8, title: "8. Changes to These Terms", icon: <Calendar className="size-6" /> },
            { id: 9, title: "9. Contact", icon: <Phone className="size-6" /> }
          ].map((section, idx) => (
            <div key={idx} className="group">
              <h2 className="font-headline font-black text-2xl md:text-3xl text-on-surface mb-6 flex items-center gap-4">
                <span className="text-primary/20 group-hover:text-primary transition-colors">{section.icon}</span>
                {t(section.title)}
              </h2>
              <div className="space-y-4 pl-10">
                {idx === 0 && (
                  <>
                    <p className="font-body text-on-surface-variant leading-relaxed text-lg">
                      {t("KrushiSense is an AI-assisted crop recommendation tool designed to help farmers in Maharashtra and across India make informed decisions about which crops to grow based on soil and environmental parameters.")}
                    </p>
                    <div className="bg-amber-500/10 border-l-4 border-amber-500 p-6 rounded-r-2xl mt-6">
                       <p className="font-body text-amber-700 dark:text-amber-400 font-bold text-lg">
                         {t("KrushiSense is a guidance tool — not a substitute for professional agricultural advice. Always verify recommendations with your local Krishi Vigyan Kendra (KVK) or a qualified agronomist before making major farming decisions.")}
                       </p>
                    </div>
                  </>
                )}
                {idx === 1 && (
                  <>
                    <p className="font-body text-on-surface-variant leading-relaxed text-lg">
                      {t("Crop recommendations generated by KrushiSense are based on machine learning models trained on agricultural datasets. While we strive for accuracy, we make no guarantees about:")}
                    </p>
                    <ul className="space-y-4 mt-4">
                      {[
                        "The suitability of any recommended crop for your specific land.",
                        "Crop yield, profit, or harvest outcomes.",
                        "Accuracy of recommendations under extreme or unusual soil and climate conditions.",
                        "Results if the input values you enter are inaccurate or estimated."
                      ].map((item, i) => (
                        <li key={i} className="flex gap-4 items-center font-body text-on-surface-variant text-base md:text-lg">
                          <div className="size-1.5 rounded-full bg-primary shrink-0" />
                          {t(item)}
                        </li>
                      ))}
                    </ul>
                    <p className="font-body text-primary font-bold mt-6 underline underline-offset-4">
                      {t("For best results, use values from a certified soil test report. KVKs across Maharashtra offer soil testing from ₹100–₹200 per sample.")}
                    </p>
                  </>
                )}
                {idx === 2 && <p className="font-body text-on-surface-variant leading-relaxed text-lg">{t("KrushiSense and its developers are not responsible for any crop failure, financial loss, or damage that may result from following recommendations provided by this application. Agriculture involves many unpredictable factors — weather, pests, market prices — that are beyond the scope of any recommendation tool. Use KrushiSense as one input among many, not as your only decision-making source.")}</p>}
                {idx === 3 && <p className="font-body text-on-surface-variant leading-relaxed text-lg">{t("The Krishi Vigyan Kendra locations, phone numbers, and service information shown on KrushiSense are sourced from ICAR official records and individual KVK websites. While we do our best to keep this information accurate, details may change. Always call ahead to confirm a KVK's services and hours before visiting.")}</p>}
                {idx === 4 && <p className="font-body text-on-surface-variant leading-relaxed text-lg">{t("Fertilizer dosage calculations shown on KrushiSense are based on ICAR published guidelines and standard agronomic formulas. These are estimates only. Actual fertilizer requirements vary by soil condition, irrigation, crop variety, and season. Consult an agronomist or your local KVK before applying fertilizers.")}</p>}
                {idx === 5 && (
                  <>
                    <p className="font-body text-on-surface-variant leading-relaxed text-lg mb-4">{t("You agree not to:")}</p>
                    <ul className="space-y-4">
                      {[
                        "Use KrushiSense for any unlawful purpose.",
                        "Attempt to reverse engineer, scrape, or copy the recommendation model or datasets.",
                        "Misrepresent KrushiSense recommendations as certified agricultural advice."
                      ].map((item, i) => (
                        <li key={i} className="p-4 rounded-xl bg-surface-container-low border border-on-surface/5 font-body text-on-surface-variant">{t(item)}</li>
                      ))}
                    </ul>
                  </>
                )}
                {idx === 6 && <p className="font-body text-on-surface-variant leading-relaxed text-lg">{t("KrushiSense is provided free of charge. We do not guarantee uninterrupted availability of the service. We may update, modify, or temporarily suspend the app at any time without prior notice.")}</p>}
                {idx === 7 && <p className="font-body text-on-surface-variant leading-relaxed text-lg">{t("We may update these Terms of Service as the application evolves. Changes will be reflected on this page with an updated date. Continued use of KrushiSense after changes constitutes your acceptance of the new terms.")}</p>}
                {idx === 8 && (
                   <p className="font-body text-on-surface-variant leading-relaxed text-lg">
                    {t("Questions about these terms? Contact us via the Contact Support page.")}
                  </p>
                )}
              </div>
            </div>
          ))}
        </div>
      </motion.div>
    </div>
  );
};
